-- MySQL Script generated by MySQL Workbench
-- lun 27 mar 2017 12:30:27 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fotocopias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fotocopias` ;

-- -----------------------------------------------------
-- Schema fotocopias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fotocopias` DEFAULT CHARACTER SET latin1 ;
USE `fotocopias` ;

-- -----------------------------------------------------
-- Table `fotocopias`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoUsuario` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dinero` DECIMAL(5,2) NOT NULL,
  `apellidos` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `nombre` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `realm` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `emailVerified` TINYINT(1) NULL DEFAULT NULL,
  `verificationToken` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Alumno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `apellido1` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `apellido2` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `nombre` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `fechaNac` DATE NULL DEFAULT NULL,
  `movil` VARCHAR(9) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `padre` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `madre` VARCHAR(48) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `telCasa` VARCHAR(9) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `movilPadre` VARCHAR(9) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `movilMadre` VARCHAR(9) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `domicilio` VARCHAR(67) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `cp` VARCHAR(5) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `localidad` VARCHAR(21) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `provincia` VARCHAR(8) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Profesor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(19) CHARACTER SET 'utf8' NOT NULL,
  `nombre` VARCHAR(19) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dni` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `movil` VARCHAR(9) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `departamento` VARCHAR(4) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Grupo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tutor` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `anyo` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  `Grupo` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `subGrupo` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `ensenanza` VARCHAR(80) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `archivos` VARCHAR(300) CHARACTER SET 'utf8' NOT NULL,
  `archivosDescargar` VARCHAR(300) CHARACTER SET 'utf8' NOT NULL,
  `curso` INT(11) NULL DEFAULT NULL,
  `horarioVisita` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Materia` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Materia` (
  `codigo` VARCHAR(6) CHARACTER SET 'utf8' NOT NULL,
  `Materia` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ensenanza` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `curso` VARCHAR(1) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`MateriaImpartida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`MateriaImpartida` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`MateriaImpartida` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Materia` VARCHAR(6) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Profesor` VARCHAR(6) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Grupo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index5` (`Materia` ASC, `Profesor` ASC, `Grupo` ASC),
  INDEX `fk_MateriasImpartidas_Materias1_idx` (`Materia` ASC),
  INDEX `fk_MateriasImpartidas_Profesores1_idx` (`Profesor` ASC),
  INDEX `fk_MateriaImpartida_Grupo1_idx` (`Grupo` ASC),
  CONSTRAINT `FK_17D5104F5B7406D9`
    FOREIGN KEY (`Profesor`)
    REFERENCES `fotocopias`.`Profesor` (`id`),
  CONSTRAINT `FK_17D5104F6DF05284`
    FOREIGN KEY (`Materia`)
    REFERENCES `fotocopias`.`Materia` (`codigo`),
  CONSTRAINT `FK_17D5104F8C0E9BD3`
    FOREIGN KEY (`Grupo`)
    REFERENCES `fotocopias`.`Grupo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`MateriaMatriculada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`MateriaMatriculada` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`MateriaMatriculada` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `expediente` INT(11) NULL DEFAULT NULL,
  `Materia` VARCHAR(6) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Profesor` VARCHAR(6) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `anyo` VARCHAR(7) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index4` (`expediente` ASC, `Materia` ASC, `anyo` ASC),
  INDEX `IDX_E38E55AD59CA413` (`expediente` ASC),
  INDEX `fk_MateriasMatriculadas_Materias1_idx` (`Materia` ASC),
  INDEX `fk_MateriasMatriculadas_Profesores1_idx` (`Profesor` ASC),
  CONSTRAINT `FK_E38E55A5B7406D9`
    FOREIGN KEY (`Profesor`)
    REFERENCES `fotocopias`.`Profesor` (`id`),
  CONSTRAINT `FK_E38E55A6DF05284`
    FOREIGN KEY (`Materia`)
    REFERENCES `fotocopias`.`Materia` (`codigo`),
  CONSTRAINT `FK_E38E55AD59CA413`
    FOREIGN KEY (`expediente`)
    REFERENCES `fotocopias`.`Alumno` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Matricula` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Matricula` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `expediente` INT(11) NULL DEFAULT NULL,
  `grupo` INT(11) NULL DEFAULT NULL,
  `curso` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `fotocopias`.`Conserje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Conserje` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Conserje` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(19) CHARACTER SET 'utf8' NOT NULL,
  `nombre` VARCHAR(19) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dni` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `fotocopias`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fotocopias`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `fotocopias`.`Administrador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(19) CHARACTER SET 'utf8' NOT NULL,
  `nombre` VARCHAR(19) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dni` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
